name: storybook

on:
  push:
    paths:
      - ./.github/workflows/storybook.yml
      - ./package.json
      - ./src/components/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy
    steps:
      - name: Trigger webhook
        run: curl ${{ secrets.STORYBOOK_WEBSITE_DEPLOY_WEBHOOK }}
